import React from 'react'
import Img3 from './media/3.jpg'

export const Cap3 = ()=>(
    <div className="escena">
        <div className="historia">
        <p>Poco a poco me ausente de clases hasta el punto de ya no ir a la escuela, también Luna poco a poco dejo de aparecerse, pensando yo que ya no la volvería ver y sentirme incomodo cuando me hablaba cuando estaba con otras personas.
        Solo frecuentaba a un par de amigos entre ellos Gama al cual le gustaba mucho la lectura precisamente él me recomendó un libro llamado” Las clavículas de Salomón” me lo paso por pdf, solo leí el principio pues no me llamó mucho la atención, en lo personal me gusta leer los libros en físico, el libro trataba de cómo establecer contacto con demonios, ángeles etc. explicando cada detalle el cómo invocarlos. Lo deje de leer pues ese tipo de temas no me llamaba mucha la atención en ese momento.
        Después entre a otra escuela, en el primer semestre me sucedió la experiencia más aterradora. Cuando estaba en casa después de un día común yo dormía como a las tres o cuatro de la mañana pero esa noche me empezó a dar demasiado sueño de la nada al mirar la hora apenas daría la media noche, no aguante más y me fui a la cama y en cuestión de segundos me quede dormido, para solo despertar con el ladrido de Nola mi perrita, de la nada el ladrido se transformó en un sonido de baja frecuencia el cual me dejó noqueado.
        al regresar en sí recuerdo que me encontraba recostado en una habitación completamente blanca y muy luminosa, solo podía mover mis ojos además podía sentir seis presencias tres de cada lado no las podía ver, ni escuchar tan solo sentía su presencia a mi costados , pero por un momento al mismo tiempo me podía ver recostado aproximadamente a un menos de un metro de mi cuerpo de repente solo sentí que solo estaba mi cuerpo sin conciencia o alma, al percatarme de eso comencé a moverme y hacer ruidos extraños el cual mi cuerpo reacciono despertando debajo de mis cobijas temblando el cual le grite a mi madre varias veces hasta que llegó preguntándome qué estaba pasado solo le respondí que prendiera la luz al hacerlo me descubrí de las cobijas temblando al mirar el reloj tan solo una hora había pasado, sintiendo un dolor no tan molesto en la parte trasera derecha de mi cabeza, mi cuerpo se sentía cortado en especial brazos y piernas dolía como si en el día hubiera hecho trabajos forzados, esa noche ya no puede dormir. en la mañana les mande mensaje a Luis y Gama para verlos y contarles lo que me había pasado pues no se los quería contar por otro medio solo en persona el cual nos pusimos de acuerdo para vernos ese mismo fin de semana.
        Al menos una semana me sentí muy raro como si no fuera yo solo una copia de mí, dudando de todo creyendo que todo era falso también tuve ese dolor de mi cabeza un par de días. El día que vi a Gama y Luis fue lo primero que les conté y al terminar Gama me contó una pequeña historia en la cual un chico había contactado con un ente, ni demonio ,ni ángel solo algo el cual tal chico le pidió el don de la sabiduría el poder de aprender mucho más rápido en menos tiempo pero a cambio que en sus últimos dos días antes de su muerte su ser le pertenecía a ese ente el cual el aceptó y así el trato quedó hecho.
        En tercer semestre fue cuando conocí a esa chica que me llamó la atención la recuerdo del primer día de presentación hace 18 meses atrás en ese tiempo ella tenía el cabello corto tal vez eso fue lo que me llamó la atención de ella en ese momento ,junto con su contraparte otra niña tan infantilizada hablando de temas que no correspondía en ese momento dándole importancia como que casi serían sus 15 años y que darían de comer y al menos para mí eso nada tenía que ver con el plan de estudio de la escuela pero regresando a la chica del cabello corto era linda pero su mirada fue la que más me intrigo no por ser hermosa ni penetrante simplemente la mantenía agachada.
        La chica de cabello corto en tercer semestre se empezó a juntar con nosotros yo y otra niña que no se despegaba de mi por más que intentará alejarme de ella me seguía a todas partes prefería estar solo que en su compañía y ahora tenía que deshacerme de dos niñas.</p>
        </div>
        <div className="imagen">
            <img src={Img3} alt=""/>
        </div>
    </div>
)